runtime: python
env: flex

entrypoint: gunicorn -b :$PORT main_backend:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.12"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  FLASK_ENV: 'production'
  MONGO_URI: 'mongodb+srv://thiagovaillant:lolzinho123.@cluster0.32wntaj.mongodb.net/monkeywitdb?retryWrites=true&w=majority&appName=Cluster0'
  JWT_SECRET_KEY: 'super-secret'
